### ISSUE TITLE
npm package CLI is broken

### ISSUE THREAD

**Issue by nshtg** [atom/tello#1]
`bin/tello` points to `../src/tello-cli`. Currently your npm package `tello` ships with compiled js, containing only a `lib` folder (`donna` only ships coffee-script and a `src` folder, thats why it is working there).

Please fix the published npm package.^^

**Comment by nshtg** [comment]
@benogle :)

**Comment by kevinsawicki** [comment]
Fixed in #2 and published in 1.0.6
